"""Add AI config management tables

Revision ID: 2a750d3863c1
Revises: 5f98d6660037
Create Date: 2025-09-06 12:55:05.341897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a750d3863c1'
down_revision = '5f98d6660037'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False, comment='提供商名称'),
    sa.Column('display_name', sa.String(length=100), nullable=False, comment='显示名称'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认配置'),
    sa.Column('api_key', sa.Text(), nullable=False, comment='API密钥'),
    sa.Column('model_name', sa.String(length=100), nullable=False, comment='模型名称'),
    sa.Column('api_url', sa.String(length=500), nullable=True, comment='API地址'),
    sa.Column('advanced_config', sa.JSON(), nullable=True, comment='高级配置参数'),
    sa.Column('total_requests', sa.Integer(), nullable=True, comment='总请求次数'),
    sa.Column('successful_requests', sa.Integer(), nullable=True, comment='成功请求次数'),
    sa.Column('failed_requests', sa.Integer(), nullable=True, comment='失败请求次数'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_configs')
    # ### end Alembic commands ###
