"""Add user_role field to User model

Revision ID: 5f98d6660037
Revises: 2312a4d52003
Create Date: 2025-09-06 11:07:10.120773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f98d6660037'
down_revision = '2312a4d52003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=20), nullable=True, comment='用户角色：SUPER_ADMIN/SITE_ADMIN/USER'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
