"""Add prompt management tables

Revision ID: 64054ef57582
Revises: 2a750d3863c1
Create Date: 2025-09-06 15:59:23.239945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64054ef57582'
down_revision = '2a750d3863c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False, comment='提示词名称'),
    sa.Column('description', sa.Text(), nullable=True, comment='提示词描述'),
    sa.Column('prompt_type', sa.String(length=50), nullable=False, comment='提示词类型：fundamental, technical'),
    sa.Column('content', sa.Text(), nullable=False, comment='提示词内容'),
    sa.Column('version', sa.Integer(), nullable=True, comment='版本号'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='是否激活'),
    sa.Column('is_default', sa.Boolean(), nullable=True, comment='是否为默认版本'),
    sa.Column('usage_count', sa.Integer(), nullable=True, comment='使用次数'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='最后使用时间'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='创建者ID'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prompts')
    # ### end Alembic commands ###
